/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.social.ecom.products.avro;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class CreateProduct extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = -6527185559514026386L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"CreateProduct\",\"namespace\":\"com.social.ecom.products.avro\",\"fields\":[{\"name\":\"name\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}},{\"name\":\"description\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}},{\"name\":\"price\",\"type\":\"float\"},{\"name\":\"stock_quantity\",\"type\":\"int\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<CreateProduct> ENCODER =
      new BinaryMessageEncoder<CreateProduct>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<CreateProduct> DECODER =
      new BinaryMessageDecoder<CreateProduct>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<CreateProduct> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<CreateProduct> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<CreateProduct> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<CreateProduct>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this CreateProduct to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a CreateProduct from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a CreateProduct instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static CreateProduct fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  @Deprecated public java.lang.String name;
  @Deprecated public java.lang.String description;
  @Deprecated public float price;
  @Deprecated public int stock_quantity;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public CreateProduct() {}

  /**
   * All-args constructor.
   * @param name The new value for name
   * @param description The new value for description
   * @param price The new value for price
   * @param stock_quantity The new value for stock_quantity
   */
  public CreateProduct(java.lang.String name, java.lang.String description, java.lang.Float price, java.lang.Integer stock_quantity) {
    this.name = name;
    this.description = description;
    this.price = price;
    this.stock_quantity = stock_quantity;
  }

  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return name;
    case 1: return description;
    case 2: return price;
    case 3: return stock_quantity;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: name = value$ != null ? value$.toString() : null; break;
    case 1: description = value$ != null ? value$.toString() : null; break;
    case 2: price = (java.lang.Float)value$; break;
    case 3: stock_quantity = (java.lang.Integer)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'name' field.
   * @return The value of the 'name' field.
   */
  public java.lang.String getName() {
    return name;
  }


  /**
   * Sets the value of the 'name' field.
   * @param value the value to set.
   */
  public void setName(java.lang.String value) {
    this.name = value;
  }

  /**
   * Gets the value of the 'description' field.
   * @return The value of the 'description' field.
   */
  public java.lang.String getDescription() {
    return description;
  }


  /**
   * Sets the value of the 'description' field.
   * @param value the value to set.
   */
  public void setDescription(java.lang.String value) {
    this.description = value;
  }

  /**
   * Gets the value of the 'price' field.
   * @return The value of the 'price' field.
   */
  public float getPrice() {
    return price;
  }


  /**
   * Sets the value of the 'price' field.
   * @param value the value to set.
   */
  public void setPrice(float value) {
    this.price = value;
  }

  /**
   * Gets the value of the 'stock_quantity' field.
   * @return The value of the 'stock_quantity' field.
   */
  public int getStockQuantity() {
    return stock_quantity;
  }


  /**
   * Sets the value of the 'stock_quantity' field.
   * @param value the value to set.
   */
  public void setStockQuantity(int value) {
    this.stock_quantity = value;
  }

  /**
   * Creates a new CreateProduct RecordBuilder.
   * @return A new CreateProduct RecordBuilder
   */
  public static com.social.ecom.products.avro.CreateProduct.Builder newBuilder() {
    return new com.social.ecom.products.avro.CreateProduct.Builder();
  }

  /**
   * Creates a new CreateProduct RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new CreateProduct RecordBuilder
   */
  public static com.social.ecom.products.avro.CreateProduct.Builder newBuilder(com.social.ecom.products.avro.CreateProduct.Builder other) {
    if (other == null) {
      return new com.social.ecom.products.avro.CreateProduct.Builder();
    } else {
      return new com.social.ecom.products.avro.CreateProduct.Builder(other);
    }
  }

  /**
   * Creates a new CreateProduct RecordBuilder by copying an existing CreateProduct instance.
   * @param other The existing instance to copy.
   * @return A new CreateProduct RecordBuilder
   */
  public static com.social.ecom.products.avro.CreateProduct.Builder newBuilder(com.social.ecom.products.avro.CreateProduct other) {
    if (other == null) {
      return new com.social.ecom.products.avro.CreateProduct.Builder();
    } else {
      return new com.social.ecom.products.avro.CreateProduct.Builder(other);
    }
  }

  /**
   * RecordBuilder for CreateProduct instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<CreateProduct>
    implements org.apache.avro.data.RecordBuilder<CreateProduct> {

    private java.lang.String name;
    private java.lang.String description;
    private float price;
    private int stock_quantity;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.social.ecom.products.avro.CreateProduct.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.name)) {
        this.name = data().deepCopy(fields()[0].schema(), other.name);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.description)) {
        this.description = data().deepCopy(fields()[1].schema(), other.description);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
      if (isValidValue(fields()[2], other.price)) {
        this.price = data().deepCopy(fields()[2].schema(), other.price);
        fieldSetFlags()[2] = other.fieldSetFlags()[2];
      }
      if (isValidValue(fields()[3], other.stock_quantity)) {
        this.stock_quantity = data().deepCopy(fields()[3].schema(), other.stock_quantity);
        fieldSetFlags()[3] = other.fieldSetFlags()[3];
      }
    }

    /**
     * Creates a Builder by copying an existing CreateProduct instance
     * @param other The existing instance to copy.
     */
    private Builder(com.social.ecom.products.avro.CreateProduct other) {
      super(SCHEMA$);
      if (isValidValue(fields()[0], other.name)) {
        this.name = data().deepCopy(fields()[0].schema(), other.name);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.description)) {
        this.description = data().deepCopy(fields()[1].schema(), other.description);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.price)) {
        this.price = data().deepCopy(fields()[2].schema(), other.price);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.stock_quantity)) {
        this.stock_quantity = data().deepCopy(fields()[3].schema(), other.stock_quantity);
        fieldSetFlags()[3] = true;
      }
    }

    /**
      * Gets the value of the 'name' field.
      * @return The value.
      */
    public java.lang.String getName() {
      return name;
    }


    /**
      * Sets the value of the 'name' field.
      * @param value The value of 'name'.
      * @return This builder.
      */
    public com.social.ecom.products.avro.CreateProduct.Builder setName(java.lang.String value) {
      validate(fields()[0], value);
      this.name = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'name' field has been set.
      * @return True if the 'name' field has been set, false otherwise.
      */
    public boolean hasName() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'name' field.
      * @return This builder.
      */
    public com.social.ecom.products.avro.CreateProduct.Builder clearName() {
      name = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'description' field.
      * @return The value.
      */
    public java.lang.String getDescription() {
      return description;
    }


    /**
      * Sets the value of the 'description' field.
      * @param value The value of 'description'.
      * @return This builder.
      */
    public com.social.ecom.products.avro.CreateProduct.Builder setDescription(java.lang.String value) {
      validate(fields()[1], value);
      this.description = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'description' field has been set.
      * @return True if the 'description' field has been set, false otherwise.
      */
    public boolean hasDescription() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'description' field.
      * @return This builder.
      */
    public com.social.ecom.products.avro.CreateProduct.Builder clearDescription() {
      description = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'price' field.
      * @return The value.
      */
    public float getPrice() {
      return price;
    }


    /**
      * Sets the value of the 'price' field.
      * @param value The value of 'price'.
      * @return This builder.
      */
    public com.social.ecom.products.avro.CreateProduct.Builder setPrice(float value) {
      validate(fields()[2], value);
      this.price = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'price' field has been set.
      * @return True if the 'price' field has been set, false otherwise.
      */
    public boolean hasPrice() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'price' field.
      * @return This builder.
      */
    public com.social.ecom.products.avro.CreateProduct.Builder clearPrice() {
      fieldSetFlags()[2] = false;
      return this;
    }

    /**
      * Gets the value of the 'stock_quantity' field.
      * @return The value.
      */
    public int getStockQuantity() {
      return stock_quantity;
    }


    /**
      * Sets the value of the 'stock_quantity' field.
      * @param value The value of 'stock_quantity'.
      * @return This builder.
      */
    public com.social.ecom.products.avro.CreateProduct.Builder setStockQuantity(int value) {
      validate(fields()[3], value);
      this.stock_quantity = value;
      fieldSetFlags()[3] = true;
      return this;
    }

    /**
      * Checks whether the 'stock_quantity' field has been set.
      * @return True if the 'stock_quantity' field has been set, false otherwise.
      */
    public boolean hasStockQuantity() {
      return fieldSetFlags()[3];
    }


    /**
      * Clears the value of the 'stock_quantity' field.
      * @return This builder.
      */
    public com.social.ecom.products.avro.CreateProduct.Builder clearStockQuantity() {
      fieldSetFlags()[3] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public CreateProduct build() {
      try {
        CreateProduct record = new CreateProduct();
        record.name = fieldSetFlags()[0] ? this.name : (java.lang.String) defaultValue(fields()[0]);
        record.description = fieldSetFlags()[1] ? this.description : (java.lang.String) defaultValue(fields()[1]);
        record.price = fieldSetFlags()[2] ? this.price : (java.lang.Float) defaultValue(fields()[2]);
        record.stock_quantity = fieldSetFlags()[3] ? this.stock_quantity : (java.lang.Integer) defaultValue(fields()[3]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<CreateProduct>
    WRITER$ = (org.apache.avro.io.DatumWriter<CreateProduct>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<CreateProduct>
    READER$ = (org.apache.avro.io.DatumReader<CreateProduct>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    out.writeString(this.name);

    out.writeString(this.description);

    out.writeFloat(this.price);

    out.writeInt(this.stock_quantity);

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      this.name = in.readString();

      this.description = in.readString();

      this.price = in.readFloat();

      this.stock_quantity = in.readInt();

    } else {
      for (int i = 0; i < 4; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          this.name = in.readString();
          break;

        case 1:
          this.description = in.readString();
          break;

        case 2:
          this.price = in.readFloat();
          break;

        case 3:
          this.stock_quantity = in.readInt();
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}










